name: Autograde Rational Assignment

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      BASE_URL: https://raw.githubusercontent.com/UofL-CSE-AutoGrader/Rational_BigInteger_AutoGrader/refs/heads/main

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up C++ and CMake
        uses: lukka/get-cmake@latest
          

      - name: Verify autograder.yml has not been modified
        run: |
          wget -O autograder.yml $BASE_URL/autograder/autograder.yml
          if ! diff -q .github/workflows/autograder.yml autograder.yml; then
            echo "The local autograder.yml appears to have been modified."
            echo "Please update your autograder.yml file."
            exit 1
          else
            echo "The local autograder.yml has been validated."
          fi

      - name: Install GoogleTest dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtest-dev cmake g++ wget

      - name: Remove existing protected files
        run: |
          rm -f include/Rational.hpp
          rm -f CMakeLists.txt

      - name: Download protected autograder files
        run: |
          wget -O include/Rational.hpp $BASE_URL/includes/Rational.hpp
          wget -O CMakeLists.txt $BASE_URL/cmake/CMakeLists.txt

      - name: Configure project
        run: cmake -B build

      - name: Build project
        run: cmake --build build

      - name: Run tests
        run: cd build && ctest --output-on-failure
